# -*- coding: utf-8 -*-
"""C-108_BellCurve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xOOoobTbZXmtIzBn02_L_fjQJkGaQLbM
"""

import random 
import plotly.express as px
import plotly.figure_factory as pf


dice_result = []
count = []

for i in range(0,100):
  dice1 = random.randint(1,6)
  dice2 = random.randint(1,6)
  dice_result.append(dice1+dice2)
  count.append(i)

import plotly.express as px
fig = px.bar(x = dice_result, y= count)
fig.show()

fig = pf.create_distplot([dice_result],["Result"])
fig.show()

from google.colab import files
data_to_load = files.upload()

import pandas as pd
import csv
df = pd.read_csv("C-108_bellcurve.csv")
fig = pf.create_distplot([df["Height(Inches)"].tolist()], ["Height"], show_hist=False)
fig.show()

fig = pf.create_distplot ([df["Weight(Pounds)"].tolist()] ,["Weight"], show_hist=False)
fig.show()